version: '3.1'
services:
   jenkins:
      container_name: jenkins_master
      image: jenkins
      build:
        context: ./
      ports:
         - "8080:8080"
      volumes:
         - "$PWD/data:/var/jenkins_home"
         - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
         - SEED_JOBS_URL=https://github.com/Savostov-Arseny/dsl-jobs.git
      networks:
         - net
      secrets:
         - juser
         - jpass
         - dockeruser
         - dockerpassword
         - ansible_host
         - id_rsa
networks:
   net:

secrets:
  juser:
    file: ./data/juser
  jpass:
    file: ./data/jpass
  dockeruser:
    file:  ./data/dockeruser
  dockerpassword:
    file:  ./data/dockerpassword
  ansible_host:
    file: ./data/ansible_host
  id_rsa:
    file: /home/ubuntu/.ssh/id_rsa
